// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/pay.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "pay";

/** Thông tin ví Pay */
export interface Pay {
  id: number;
  userId: number;
  /** số tiền */
  tien: string;
  /** "open" hoặc "locked" */
  status: string;
  updatedAt: string;
}

/** Request để lấy ví theo userId */
export interface GetPayByUserIdRequest {
  userId: number;
}

/** Request cộng/trừ tiền */
export interface UpdateMoneyRequest {
  userId: number;
  /** số tiền thay đổi, có thể âm hoặc dương */
  amount: number;
}

/** Request thay đổi trạng thái tài khoản (lock/unlock) */
export interface UpdateStatusRequest {
  userId: number;
  /** "open" hoặc "locked" */
  status: string;
}

/** Request khởi tạo ví mới khi tạo user */
export interface CreatePayRequest {
  userId: number;
}

export interface CreatePayOrderRequest {
  userId: number;
  amount: number;
  username: string;
}

/** Response chung */
export interface PayResponse {
  pay: Pay | undefined;
  message: string;
}

export interface QrResponse {
  qr: string;
  username: string;
}

export interface Empty {
}

export interface Finance {
  id: number;
  user_id: number;
  /** NAP hoặc RUT */
  type: string;
  amount: number;
  create_at: string;
}

export interface CreateFinanceRequest {
  user_id: number;
  /** NAP hoặc RUT */
  type: string;
  amount: number;
}

export interface GetFinanceByUserRequest {
  user_id: number;
}

export interface FinanceResponse {
  finance: Finance | undefined;
}

export interface ListFinanceResponse {
  finances: Finance[];
}

export interface FinanceSummaryResponse {
  total_nap: number;
  total_rut: number;
  /** tổng nạp - tổng rút */
  balance: number;
}

export const PAY_PACKAGE_NAME = "pay";

export interface PayServiceClient {
  /** Các RPC nội bộ */

  getPayByUserId(request: GetPayByUserIdRequest, metadata?: Metadata): Observable<PayResponse>;

  updateMoney(request: UpdateMoneyRequest, metadata?: Metadata): Observable<PayResponse>;

  updateStatus(request: UpdateStatusRequest, metadata?: Metadata): Observable<PayResponse>;

  createPay(request: CreatePayRequest, metadata?: Metadata): Observable<PayResponse>;

  createPayOrder(request: CreatePayOrderRequest, metadata?: Metadata): Observable<QrResponse>;
}

export interface PayServiceController {
  /** Các RPC nội bộ */

  getPayByUserId(request: GetPayByUserIdRequest, metadata?: Metadata): Observable<PayResponse>;

  updateMoney(request: UpdateMoneyRequest, metadata?: Metadata): Observable<PayResponse>;

  updateStatus(request: UpdateStatusRequest, metadata?: Metadata): Observable<PayResponse>;

  createPay(request: CreatePayRequest, metadata?: Metadata): Observable<PayResponse>;

  createPayOrder(request: CreatePayOrderRequest, metadata?: Metadata): Observable<QrResponse>;
}

export function PayServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getPayByUserId", "updateMoney", "updateStatus", "createPay", "createPayOrder"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PayService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PayService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAY_SERVICE_NAME = "PayService";

/** ===== SERVICE DEFINITION ===== */

export interface FinanceServiceClient {
  /** Khi nạp/rút thành công, ghi lại dòng tiền */

  createFinanceRecord(request: CreateFinanceRequest, metadata?: Metadata): Observable<FinanceResponse>;

  /** Lấy danh sách giao dịch của 1 user */

  getFinanceByUser(request: GetFinanceByUserRequest, metadata?: Metadata): Observable<ListFinanceResponse>;

  /** Lấy tất cả giao dịch (cho admin) */

  getAllFinance(request: Empty, metadata?: Metadata): Observable<ListFinanceResponse>;

  /** Thống kê tổng nạp và tổng rút */

  getFinanceSummary(request: Empty, metadata?: Metadata): Observable<FinanceSummaryResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface FinanceServiceController {
  /** Khi nạp/rút thành công, ghi lại dòng tiền */

  createFinanceRecord(request: CreateFinanceRequest, metadata?: Metadata): Observable<FinanceResponse>;

  /** Lấy danh sách giao dịch của 1 user */

  getFinanceByUser(request: GetFinanceByUserRequest, metadata?: Metadata): Observable<ListFinanceResponse>;

  /** Lấy tất cả giao dịch (cho admin) */

  getAllFinance(request: Empty, metadata?: Metadata): Observable<ListFinanceResponse>;

  /** Thống kê tổng nạp và tổng rút */

  getFinanceSummary(request: Empty, metadata?: Metadata): Observable<FinanceSummaryResponse>;
}

export function FinanceServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createFinanceRecord", "getFinanceByUser", "getAllFinance", "getFinanceSummary"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FinanceService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FinanceService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FINANCE_SERVICE_NAME = "FinanceService";
