// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/pay.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "pay";

/** Thông tin ví Pay */
export interface Pay {
  id: number;
  userId: number;
  /** số tiền */
  tien: string;
  /** "open" hoặc "locked" */
  status: string;
  updatedAt: string;
}

/** Request để lấy ví theo userId */
export interface GetPayByUserIdRequest {
  userId: number;
}

/** Request cộng/trừ tiền */
export interface UpdateMoneyRequest {
  userId: number;
  /** số tiền thay đổi, có thể âm hoặc dương */
  amount: number;
}

/** Request thay đổi trạng thái tài khoản (lock/unlock) */
export interface UpdateStatusRequest {
  userId: number;
  /** "open" hoặc "locked" */
  status: string;
}

/** Request khởi tạo ví mới khi tạo user */
export interface CreatePayRequest {
  userId: number;
}

export interface CreatePayOrderRequest {
  userId: number;
  amount: number;
  username: string;
}

/** Response chung */
export interface PayResponse {
  pay: Pay | undefined;
  message: string;
}

export interface QrResponse {
  qr: string;
  username: string;
}

export const PAY_PACKAGE_NAME = "pay";

export interface PayServiceClient {
  /** Các RPC nội bộ */

  getPayByUserId(request: GetPayByUserIdRequest, metadata?: Metadata): Observable<PayResponse>;

  updateMoney(request: UpdateMoneyRequest, metadata?: Metadata): Observable<PayResponse>;

  updateStatus(request: UpdateStatusRequest, metadata?: Metadata): Observable<PayResponse>;

  createPay(request: CreatePayRequest, metadata?: Metadata): Observable<PayResponse>;

  createPayOrder(request: CreatePayOrderRequest, metadata?: Metadata): Observable<QrResponse>;
}

export interface PayServiceController {
  /** Các RPC nội bộ */

  getPayByUserId(request: GetPayByUserIdRequest, metadata?: Metadata): Observable<PayResponse>;

  updateMoney(request: UpdateMoneyRequest, metadata?: Metadata): Observable<PayResponse>;

  updateStatus(request: UpdateStatusRequest, metadata?: Metadata): Observable<PayResponse>;

  createPay(request: CreatePayRequest, metadata?: Metadata): Observable<PayResponse>;

  createPayOrder(request: CreatePayOrderRequest, metadata?: Metadata): Observable<QrResponse>;
}

export function PayServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getPayByUserId", "updateMoney", "updateStatus", "createPay", "createPayOrder"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PayService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PayService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAY_SERVICE_NAME = "PayService";
